# Generated by Django 5.2.8 on 2025-12-08 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_order_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('dispatched', 'Dispatched'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='preparing', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='shop.order')),
            ],
        ),
    ]
