# Generated by Django 5.2.8 on 2025-12-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('shop', '0003_order_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('shipped', 'Shipped'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='preparing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
