# Generated by Django 5.2.8 on 2025-12-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_estimated_delivery_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='estimated_delivery_time',
            new_name='eta',
        ),
    ]
